FROM jupyter/base-notebook

Maintainer Meiert Grootes <m.grootes@esciencecenter.nl>

RUN conda install flask
RUN pip install import_ipynb

RUN mkdir /home/jovyan/input
RUN mkdir /home/jovyan/code
RUN mkdir /home/jovyan/output

RUN chown -R 1000:100 /home/jovyan/input
RUN chown -R 1000:100 /home/jovyan/code
RUN chown -R 1000:100 /home/jovyan/output


ENTRYPOINT ["tini", "-g", "--"]

ENV FLASK_APP /home/jovyan/code/corpusrepresentationapi.py
ENV FLASK_RUN_HOST 0.0.0.0

RUN cd /home/jovyan/code

CMD ["flask" , "run"]
